language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: pktseqBAoZ+bld1QV7WptSPX50QnUJNKAbFWLYaUvCqGNk2PXK9ojoKssUnpMVODB8FTRSCYgyJtkIkXu/+90hYiuEXDCJnGSMswpOWnESB/z20d4/ycDYJvCYQeF2DnCpcykRm3o92AYuXYubZiqmgoInaMp9ydqKdRVCveROwGupDYxlPUMQflgLVJc+W74t5W+aWGtexZWPrr3TE0Th2PS9Wr6peLZ0YDJA8UigHK5IY5u7WwGhqWga0bO22C3TKQpHFYHHPoJnMIHIibMBwpZuuFmKXoInOliPz9bfQTka3cRm78ALNfeSG2BYiFoEk1E8iw5r0Ujd3cUQmSf3eYx+xvA5YYN1cReIQ6t4joaUd/IYS3i3ahYrubXtN4yt+UsZsYBfKZJCeqXT0JWt/WC/nxVnEE6hs7GMo5xp0JlXwmqnJ8y4vP9/FIGtFn6B67tcrPyPX7Spkewa01IUgjROpB6k3bLaNVpjlszwfzI/6gLPGBUZCCr8gveKSyEQdRfu/jiEBLe0U391nibT2sUnjjTiqgbyY80+eCj4jGq5tImhsJbsXNsFaOUQYyGhsk5WMsPOLiIClw/QCfBwxUMaiWGucUNjlG8NAvFI7ktOfuD2q5j9jc/lfjSj9xj2tdas2/4ZRzGVgf8ExlZ4UpDZgKP4s1bB6j7z2KQ2g=
